routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

Route::get('/dashboard', [DashboardController::class, 'dashboard'])->middleware(['auth'])->name('dashboard');

//Company Master
Route::get('/company', [CompanyController::class, 'index'])->middleware(['auth'])->name('company');
Route::get('/company/{id}/edit', [CompanyController::class, 'edit'])->middleware(['auth'])->name('company.edit');
Route::put('/company/{id}', [CompanyController::class, 'update'])->middleware(['auth'])->name('company.update');

//Category Master
Route::get('/category', [CategoryController::class, 'index'])->middleware(['auth'])->name('category.index');
Route::get('/category/edit', [CategoryController::class, 'edit'])->name('editCategory');
route::post('/category/update', [CategoryController::class, 'update'])->name('updateCategory');
Route::post('/category/store', [CategoryController::class, 'store'])->name('storeCategory');
Route::get('/category/delete/{id}', [CategoryController::class, 'delete'])->name('deleteCategory');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
});

//Facebook login
Route::get('auth/facebook', [SocialController::class, 'facebookRedirect']);
Route::get('auth/facebook/callback', [SocialController::class, 'loginWithFacebook']);

//Google login
Route::get('auth/google', [SocialController::class, 'redirectToGoogle']);
Route::get('auth/google/callback', [SocialController::class, 'handleGoogleCallback']);

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'fb_id',
        'google_id'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Support\Arr;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{

    function __construct()
    {
         $this->middleware('permission:user-list|user-create|user-edit|user-delete', ['only' => ['index','store']]);
         $this->middleware('permission:user-create', ['only' => ['create','store']]);
         $this->middleware('permission:user-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:user-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = User::orderBy('id','DESC')->paginate(5);
        return view('users.index',compact('data'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::pluck('name','name')->all();
        return view('users.create',compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|same:confirm-password',
            'roles' => 'required'
        ]);
    
        $input = $request->all();
        $input['password'] = Hash::make($input['password']);
    
        $user = User::create($input);
        $user->assignRole($request->input('roles'));
    
        return redirect()->route('users.index')
                        ->with('success','User created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view('users.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // $user = User::find($id);
        // $roles = Role::pluck('name','name')->all();
        // $userRole = $user->roles->pluck('name')->all();
        
        // return view('users.edit',compact('user','roles','userRole'));

        $user = User::find($id);
        $roles = Role::pluck('name','name')->all();
        $userRole = $user->roles->pluck('name','name')->all();
    
        return view('users.edit',compact('user','roles','userRole'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email,'.$id,
            'password' => 'same:confirm-password',
            'roles' => 'required'
        ]);
    
        $input = $request->all();
        if(!empty($input['password'])){ 
            $input['password'] = Hash::make($input['password']);
        }else{
            $input = Arr::except($input,array('password'));    
        }
    
        $user = User::find($id);
        $user->update($input);
        DB::table('model_has_roles')->where('model_id',$id)->delete();
    
        $user->assignRole($request->input('roles'));
    
        return redirect()->route('users.index')
                        ->with('success','User updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->route('users.index')
                        ->with('success','User deleted successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/users/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create User') }}
        </h2>
    </x-slot>

<div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">

<div class="md:mt-0 md:col-span-2">
    <form action="{{route('users.store')}}" enctype="multipart/form-data" method="POST">
        @csrf
        @method('post')
        <div class="shadow overflow-hidden sm:rounded-md w-full mx-auto">
            <div class="px-4 py-4 bg-white sm:p-6">

                @if (count($errors) > 0)
                <div class="alert alert-danger">
                  <strong>Whoops!</strong> There were some problems with your input.<br><br>
                  <ul>
                     @foreach ($errors->all() as $error)
                       <li>{{ $error }}</li>
                     @endforeach
                  </ul>
                </div>
              @endif

                <div class="grid grid-cols-6 gap-6">



                    <div class="col-span-6 sm:col-span-2">
                        <label for="name" class="block text-sm font-medium text-gray-700"> Name </label>
                        <input type="text"  name="name" id="name"
                             autocomplete="given-name" required
                            class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" >
                      
                    </div>

                    <div class="col-span-6 sm:col-span-2">
                        <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
                        <input type="email"  name="email" id="email" 
                            autocomplete="family-name"
                            class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" >
                       
                    </div>

                    <div class="col-span-6 sm:col-span-2">
                        <label for="password" class="block text-sm font-medium text-gray-700">Password</label>
                        <input type="password"  name="password" id="password" 
                            autocomplete="family-name"
                            class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" >
                       
                    </div>

                    <div class="col-span-6 sm:col-span-2">
                        <label for="confirm-password" class="block text-sm font-medium text-gray-700">Confirm Password</label>
                        <input type="password"  name="confirm-password" id="confirm-password" 
                            autocomplete="family-name"
                            class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" >
                       
                    </div>

                    <div class="col-span-6 sm:col-span-6 lg:col-span-2">
                        <label for="role" class="block text-sm font-medium text-gray-700">Role</label>
                        <select id="role" name="role" autocomplete="role"
                            class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                            >
                            @foreach ($roles as $r)
                                <option>{{$r}}</option>
                            @endforeach
                            
                        </select>
                    </div>

               



                </div>
                
                  

              
           
            <div class="px-4 py-3 mt-2 bg-gray-50 text-right sm:px-6">

                <button type="submit"
                    class="inline-flex justify-center py-2 px-14 border border-transparent shadow-sm text-sm font-semibold rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    Save
                </button>



                <a href="{{ URL::previous() }}">
                    <button type="button"
                        class="inline-flex justify-center py-2 px-14 border border-transparent shadow-sm text-sm font-semibold rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
                        Back
                    </button>
                </a>
            </div>
        </div>
    </form>
</div>

        </div>
    </div>
</div>

</x-app-layout>

resources/views/users/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit User') }}
        </h2>
    </x-slot>

<div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">

<div class="md:mt-0 md:col-span-2">
    <form action="{{route('users.update', $user->id)}}" enctype="multipart/form-data" method="POST">
        @csrf
        @method('PUT')
        <div class="shadow overflow-hidden sm:rounded-md w-full mx-auto">
            <div class="px-4 py-4 bg-white sm:p-6">

                @if (count($errors) > 0)
                <div class="alert alert-danger">
                  <strong>Whoops!</strong> There were some problems with your input.<br><br>
                  <ul>
                     @foreach ($errors->all() as $error)
                       <li>{{ $error }}</li>
                     @endforeach
                  </ul>
                </div>
              @endif

                <div class="grid grid-cols-6 gap-6">



                    <div class="col-span-6 sm:col-span-2">
                        <label for="name" class="block text-sm font-medium text-gray-700">Name </label>
                        <input type="text" value="{{$user->name}}"  name="name" id="name"
                             autocomplete="given-name" required
                            class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" >
                      
                    </div>

                    <div class="col-span-6 sm:col-span-2">
                        <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
                        <input type="email" value="{{$user->email}}"  name="email" id="email" 
                            autocomplete="family-name"
                            class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" >
                       
                    </div>

                    <div class="col-span-6 sm:col-span-2">
                        <label for="password" class="block text-sm font-medium text-gray-700">Password</label>
                        <input type="password"   name="password" id="password" 
                            autocomplete="family-name"
                            class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" >
                       
                    </div>

                    <div class="col-span-6 sm:col-span-2">
                        <label for="confirm-password" class="block text-sm font-medium text-gray-700">Confirm Password</label>
                        <input type="password"   name="confirm-password" id="confirm-password" 
                            autocomplete="family-name"
                            class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" >
                       
                    </div>

                    <div class="col-span-6 sm:col-span-6 lg:col-span-2">
                        <label for="role" class="block text-sm font-medium text-gray-700">Role</label>
                        {{-- <select id="role" name="roles" autocomplete="role"
                            class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" required
                            >
                           
                            <option value="">Select Role</option>
                            @foreach ($roles as $item)
                                <option value="{{$item}}" {{ $userRole[0] == $item ? 'selected' : '' }}>{{$item}}</option>
                            @endforeach
                            
                        </select> --}}
                        {!! Form::select('roles[]', $roles,$userRole, array('class' => 'mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm')) !!}
                    </div>

               



                </div>
                
                  

              
           
            <div class="px-4 py-3 mt-2 bg-gray-50 text-right sm:px-6">

                <button type="submit"
                    class="inline-flex justify-center py-2 px-14 border border-transparent shadow-sm text-sm font-semibold rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    Save
                </button>



                <a href="{{ URL::previous() }}">
                    <button type="button"
                        class="inline-flex justify-center py-2 px-14 border border-transparent shadow-sm text-sm font-semibold rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
                        Back
                    </button>
                </a>
            </div>
        </div>
    </form>
</div>

        </div>
    </div>
</div>

</x-app-layout>

resources/views/users/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('User Management') }}
        </h2>
    </x-slot>

    {{-- <div class="row">
        <div class="col-lg-12 margin-tb">

            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('users.create') }}"> Create New User</a>
            </div>
        </div>
    </div>


    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif


    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Email</th>
            <th>Roles</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($data as $key => $user)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $user->name }}</td>
            <td>{{ $user->email }}</td>
            <td>
                @if(!empty($user->getRoleNames()))
                @foreach($user->getRoleNames() as $v)
                <label class="badge badge-success">{{ $v }}</label>
                @endforeach
                @endif
            </td>
            <td>
                <a class="btn btn-info" href="{{ route('users.show',$user->id) }}">Show</a>
                <a class="btn btn-primary" href="{{ route('users.edit',$user->id) }}">Edit</a>

                <a class="btn btn-danger" href="{{ route('users.edit',$user->id) }}">Delete</a>
            </td>
        </tr>
        @endforeach
    </table> --}}


    <div class="flex flex-col py-12">

        <div id="add-btn">
            @can('user-create')
            <a href="{{ route('users.create') }}">
                <button type="button"
                    class="text-white px-4 py-2 rounded bg-green-500 hover:bg-green-700 shadow mr-5 mb-3"
                    data-bs-toggle="modal" data-bs-target="#exampleModal" style="float: right">
                    Create New User
                </button>
            </a>
            @endcan

            {{-- <button class="text-white px-4 py-2 rounded bg-green-500 hover:bg-green-700 shadow mr-5 mb-3"
                style="float: right">Add</button> --}}
        </div>

        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                    <table class="w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <th scope="col"
                                    class="px-6 py-3 text-left text-xs font-bold text-gray-800 uppercase tracking-wider">
                                    Name
                                </th>
                                <th scope="col"
                                    class="px-6 py-3 text-left text-xs font-bold text-gray-800 uppercase tracking-wider">
                                    Email
                                </th>
                                <th scope="col"
                                    class="px-6 py-3 text-left text-xs font-bold text-gray-800 uppercase tracking-wider">
                                    Roles
                                </th>
                                @can('user-edit')
                                <th scope="col"
                                    class="px-6 py-3 text-left text-xs font-bold text-gray-800 uppercase tracking-wider">
                                    Action
                                </th>
                                @endcan
                            </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-200">

                            @foreach ($data as $user)
                            <tr>
                                <td class="px-6 py-4 text-gray-500 whitespace-nowrap">{{ $user->name }}</td>
                                <td class="px-6 py-4 text-gray-500 whitespace-nowrap">{{ $user->email }}</td>
                                <td class="px-6 py-4 text-gray-500 whitespace-nowrap">
                                    @if(!empty($user->getRoleNames()))
                                    @foreach($user->getRoleNames() as $v)
                                    <label >{{ $v }}</label>
                                    @endforeach
                                    @endif
                                </td>
                                @can('user-edit')
                                <td class="px-6 py-4 text-gray-500 whitespace-nowrap ">
                                    {{-- <a href="{{ route('users.show',$user->id) }}"><button class="text-white px-2 py-1 rounded bg-indigo-500 hover:bg-indigo-700 shadow-sm"
                                        >Show</button></a> --}}
                                    @can('user-edit')
                                    <a href="{{ route('users.edit',$user->id) }}"><button class="text-white px-2 py-1 rounded bg-blue-500 hover:bg-blue-700 shadow-sm"
                                        >Edit</button></a>
                                        @endcan

                                        @can('user-delete')
                                        <form action="{{route('users.destroy',$user->id)}}" method="POST" style="display: inline;">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="text-white px-2 py-1 rounded bg-red-500 hover:bg-red-700 shadow-sm">Delete</button>
                                        </form>
                                        @endcan

                                    
                                </td>
                                @endcan
                            </tr>
                            @endforeach
                        </tbody>
                    </table>



                </div>
            </div>
        </div>
    </div>


    {!! $data->render() !!}

</x-app-layout>