routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

Route::get('/dashboard', [DashboardController::class, 'dashboard'])->middleware(['auth'])->name('dashboard');

//Company Master
Route::get('/company', [CompanyController::class, 'index'])->middleware(['auth'])->name('company');
Route::get('/company/{id}/edit', [CompanyController::class, 'edit'])->middleware(['auth'])->name('company.edit');
Route::put('/company/{id}', [CompanyController::class, 'update'])->middleware(['auth'])->name('company.update');

//Category Master
Route::get('/category', [CategoryController::class, 'index'])->middleware(['auth'])->name('category.index');
Route::get('/category/edit', [CategoryController::class, 'edit'])->name('editCategory');
route::post('/category/update', [CategoryController::class, 'update'])->name('updateCategory');
Route::post('/category/store', [CategoryController::class, 'store'])->name('storeCategory');
Route::get('/category/delete/{id}', [CategoryController::class, 'delete'])->name('deleteCategory');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
});

//Facebook login
Route::get('auth/facebook', [SocialController::class, 'facebookRedirect']);
Route::get('auth/facebook/callback', [SocialController::class, 'loginWithFacebook']);

//Google login
Route::get('auth/google', [SocialController::class, 'redirectToGoogle']);
Route::get('auth/google/callback', [SocialController::class, 'handleGoogleCallback']);

require __DIR__.'/auth.php';

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class RoleController extends Controller
{

    function __construct()
    {
         $this->middleware('permission:role-list|role-create|role-edit|role-delete', ['only' => ['index','store']]);
         $this->middleware('permission:role-create', ['only' => ['create','store']]);
         $this->middleware('permission:role-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:role-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function index(Request $request)
    {
        $roles = Role::orderBy('id','DESC')->paginate(5);
        return view('roles.index',compact('roles'))->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permission = Permission::get();
        return view('roles.create',compact('permission'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'permission' => 'required',
        ]);
    
        $role = Role::create(['name' => $request->input('name')]);
        $role->syncPermissions($request->input('permission'));
    
        return redirect()->route('roles.index')
                        ->with('success','Role created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = Role::find($id);
        $rolePermissions = Permission::join("role_has_permissions","role_has_permissions.permission_id","=","permissions.id")
            ->where("role_has_permissions.role_id",$id)
            ->get();
    
        return view('roles.show',compact('role','rolePermissions'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::find($id);
        $permission = Permission::get();
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id",$id)
            ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')
            ->all();
    
        return view('roles.edit',compact('role','permission','rolePermissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'permission' => 'required',
        ]);
    
        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->save();
    
        $role->syncPermissions($request->input('permission'));
    
        return redirect()->route('roles.index')
                        ->with('success','Role updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table("roles")->where('id',$id)->delete();
        return redirect()->route('roles.index')
                        ->with('success','Role deleted successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/roles/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Role') }}
        </h2>
    </x-slot>

<div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
            

<div class="md:mt-0 md:col-span-2">
    <form action="{{route('roles.store')}}" enctype="multipart/form-data" method="POST">
        @csrf
        @method('post')
        <div class="shadow overflow-hidden sm:rounded-md w-full mx-auto">
            <div class="px-4 py-4 bg-white sm:p-6">

                @if (count($errors) > 0)
                <div class="alert alert-danger">
                  <strong>Whoops!</strong> There were some problems with your input.<br><br>
                  <ul>
                     @foreach ($errors->all() as $error)
                       <li>{{ $error }}</li>
                     @endforeach
                  </ul>
                </div>
              @endif

                <div class="grid grid-cols-6 gap-6">



                    <div class="col-span-6 sm:col-span-2">
                        <label for="name" class="block text-sm font-medium text-gray-700"> Name </label>
                        <input type="text"  name="name" id="name"
                             autocomplete="given-name" required
                            class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" >
                      
                    </div>


                    <div class="col-span-6 sm:col-span-6 lg:col-span-2">
                        <label for="role" class="block text-sm font-medium text-gray-700">Permission</label>
                        
                            @foreach ($permission as $value)
                                <label> <input type="checkbox" name="permission[]" id="" value="{{$value->id}}"> {{$value->name}}</label>
                                <br>
                            @endforeach
                            
                    </div>

               



                </div>
                
                  

              
           
            <div class="px-4 py-3 mt-2 bg-gray-50 text-right sm:px-6">

                <button type="submit"
                    class="inline-flex justify-center py-2 px-14 border border-transparent shadow-sm text-sm font-semibold rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    Save
                </button>



                <a href="{{ URL::previous() }}">
                    <button type="button"
                        class="inline-flex justify-center py-2 px-14 border border-transparent shadow-sm text-sm font-semibold rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
                        Back
                    </button>
                </a>
            </div>
        </div>
    </form>
</div>

        </div>
    </div>
</div>

</x-app-layout>

resources/views/roles/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit Role') }}
        </h2>
    </x-slot>

<div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
            

<div class="md:mt-0 md:col-span-2">
    <form action="{{route('roles.update', $role->id)}}" enctype="multipart/form-data" method="POST">
        @csrf
        @method('put')
        <div class="shadow overflow-hidden sm:rounded-md w-full mx-auto">
            <div class="px-4 py-4 bg-white sm:p-6">

                @if (count($errors) > 0)
                <div class="alert alert-danger">
                  <strong>Whoops!</strong> There were some problems with your input.<br><br>
                  <ul>
                     @foreach ($errors->all() as $error)
                       <li>{{ $error }}</li>
                     @endforeach
                  </ul>
                </div>
              @endif

                <div class="grid grid-cols-6 gap-6">



                    <div class="col-span-6 sm:col-span-2">
                        <label for="name" class="block text-sm font-medium text-gray-700"> Name </label>
                        <input type="text" value="{{$role->name}}"  name="name" id="name"
                             autocomplete="given-name" required
                            class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" >
                      
                    </div>


                    <div class="col-span-6 sm:col-span-6 lg:col-span-2">
                        <label for="role" class="block text-sm font-medium text-gray-700">Permission</label>
                        
                            {{-- @foreach ($permission as $value)
                                <label> <input type="checkbox" name="permission[]"  id=""> {{$value->name}}</label>
                                <br>
                            @endforeach --}}
                            @foreach($permission as $value)
                            <label>{{ Form::checkbox('permission[]', $value->id, in_array($value->id, $rolePermissions) ? true : false, array('class' => 'name')) }}
                            {{ $value->name }}</label>
                        <br/>
                        @endforeach
                            
                    </div>

               



                </div>
                
                  

              
           
            <div class="px-4 py-3 mt-2 bg-gray-50 text-right sm:px-6">

                <button type="submit"
                    class="inline-flex justify-center py-2 px-14 border border-transparent shadow-sm text-sm font-semibold rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    Save
                </button>



                <a href="{{ URL::previous() }}">
                    <button type="button"
                        class="inline-flex justify-center py-2 px-14 border border-transparent shadow-sm text-sm font-semibold rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
                        Back
                    </button>
                </a>
            </div>
        </div>
    </form>
</div>

        </div>
    </div>
</div>

</x-app-layout>

resources/views/roles/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Role Management') }}
        </h2>
    </x-slot>


    <div class="flex flex-col py-12">

        <div id="add-btn">
            @can('role-create')
            <a href="{{ route('roles.create') }}">
                <button type="button"
                    class="text-white px-4 py-2 rounded bg-green-500 hover:bg-green-700 shadow mr-5 mb-3"
                    data-bs-toggle="modal" data-bs-target="#exampleModal" style="float: right">
                    Create New Role
                </button>
            </a>
            @endcan

            {{-- <button class="text-white px-4 py-2 rounded bg-green-500 hover:bg-green-700 shadow mr-5 mb-3"
                style="float: right">Add</button> --}}
        </div>

        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                    <table class="w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <th scope="col"
                                    class="px-6 py-3 text-left text-xs font-bold text-gray-800 uppercase tracking-wider">
                                    Name
                                </th>
                                @can('role-edit')
                                <th scope="col"
                                    class="px-6 py-3 text-left text-xs font-bold text-gray-800 uppercase tracking-wider">
                                    Action
                                </th>
                                @endcan
                            </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-200">

                            @foreach ($roles as $role)
                            <tr>
                                <td class="px-6 py-4 text-gray-500 whitespace-nowrap">{{ $role->name }}</td>
                                
                                @can('role-edit')
                                <td class="px-6 py-4 text-gray-500 whitespace-nowrap ">
                                    {{-- <a href="{{ route('users.show',$role->id) }}"><button
                                            class="text-white px-2 py-1 rounded bg-indigo-500 hover:bg-indigo-700 shadow-sm">Show</button></a>
                                    --}}
                                    @can('role-edit')
                                    <a href="{{ route('roles.edit',$role->id) }}"><button
                                            class="text-white px-2 py-1 rounded bg-blue-500 hover:bg-blue-700 shadow-sm">Edit</button></a>
                                    @endcan

                                    @can('role-delete')
                                    <form action="{{route('roles.destroy',$role->id)}}" method="POST" style="display: inline;">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="text-white px-2 py-1 rounded bg-red-500 hover:bg-red-700 shadow-sm">Delete</button>
                                    </form>
                            
                                    @endcan
                                </td>
                                @endcan
                            </tr>
                            @endforeach
                        </tbody>
                    </table>



                </div>
            </div>
        </div>
    </div>


    {!! $roles->render() !!}

</x-app-layout>